"""Render the analysis + raw F&G data into a markdown report."""
from __future__ import annotations

from datetime import datetime

from analyze import Analysis
from fng import FearGreed


def _signal_emoji(kind: str) -> str:
    return {
        "bullish": "[BULL]",
        "bearish": "[BEAR]",
        "contrarian": "[CONTRA]",
        "risk": "[RISK]",
    }.get(kind, "[?]")


def render(
    fng: FearGreed,
    analysis: Analysis,
    post_count: int,
    headline_count: int = 0,
) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines: list[str] = []

    lines.append(f"# Market Signals Report — {now}")
    lines.append("")
    scan_summary = f"Scanned **{post_count}** Reddit posts"
    if headline_count:
        scan_summary += f" and **{headline_count}** news headlines (last 24h)"
    scan_summary += "."
    lines.append(scan_summary)
    lines.append("")

    lines.append("## Fear & Greed Index (CNN)")
    lines.append("")
    lines.append(f"**Current: {fng.score:.0f} — {fng.rating}**")
    lines.append("")
    lines.append("| Period          | Value |")
    lines.append("|-----------------|------:|")
    lines.append(f"| Now             | {fng.score:.0f} |")
    lines.append(f"| Previous close  | {fng.previous_close:.0f} |")
    lines.append(f"| 1 week ago      | {fng.one_week_ago:.0f} |")
    lines.append(f"| 1 month ago     | {fng.one_month_ago:.0f} |")
    lines.append(f"| 1 year ago      | {fng.one_year_ago:.0f} |")
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append(analysis.summary)
    lines.append("")
    lines.append(
        f"**Retail sentiment:** {analysis.sentiment_label.replace('_', ' ').title()}  "
    )
    lines.append(f"**Vs. F&G:** {analysis.sentiment_vs_fng}")
    lines.append("")

    lines.append("## Signals")
    lines.append("")
    if not analysis.signals:
        lines.append("_No signals extracted._")
    for s in analysis.signals:
        lines.append(f"### {_signal_emoji(s.kind)} {s.title}")
        lines.append(f"_{s.kind.title()} — confidence: {s.confidence}_")
        lines.append("")
        lines.append(s.rationale)
        if s.supporting_post_urls:
            lines.append("")
            lines.append("Sources:")
            for url in s.supporting_post_urls:
                lines.append(f"- <{url}>")
        lines.append("")

    lines.append("## Most-Discussed Tickers")
    lines.append("")
    if analysis.top_tickers:
        lines.append("| Ticker | Mentions | Sentiment | Context |")
        lines.append("|--------|---------:|-----------|---------|")
        for t in analysis.top_tickers:
            ctx = t.context.replace("|", "\\|").replace("\n", " ")
            lines.append(f"| {t.ticker} | {t.mention_count} | {t.sentiment} | {ctx} |")
    else:
        lines.append("_No specific tickers stood out._")
    lines.append("")

    lines.append("## Notable Themes")
    lines.append("")
    for theme in analysis.notable_themes:
        lines.append(f"- {theme}")
    lines.append("")

    lines.append("## Contrarian Take")
    lines.append("")
    lines.append(analysis.contrarian_take)
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by simple-market-signals. Not investment advice. "
        "Retail-forum sentiment is noisy — verify any specific claim before trading._"
    )

    return "\n".join(lines)
